# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-29 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('dr_id', models.IntegerField(primary_key=True, serialize=False)),
                ('acc_num', models.IntegerField(unique=True)),
                ('father_name', models.CharField(blank=True, max_length=10, null=True)),
                ('national_code', models.IntegerField(unique=True)),
                ('is_ready_field', models.NullBooleanField(db_column='Is_Ready?')),
                ('address', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
                ('family', models.CharField(blank=True, max_length=16, null=True)),
                ('lat', models.IntegerField(blank=True, null=True)),
                ('lng', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'driver',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleTable',
            fields=[
                ('plate_number', models.IntegerField(primary_key=True, serialize=False)),
                ('colour', models.CharField(blank=True, max_length=10, null=True)),
                ('model', models.CharField(blank=True, max_length=10, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('insurance_expiration', models.IntegerField()),
            ],
            options={
                'db_table': 'vehicle_table',
                'managed': False,
            },
        ),
    ]
