# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-29 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('phone_number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('family', models.CharField(max_length=16)),
                ('gender', models.IntegerField()),
                ('birthday', models.IntegerField(blank=True, null=True)),
                ('address', models.IntegerField(blank=True, null=True)),
                ('credit', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiscountTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('percentage', models.IntegerField()),
                ('source', models.IntegerField()),
                ('destinition', models.IntegerField()),
            ],
            options={
                'db_table': 'discount_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('dr_id', models.IntegerField(primary_key=True, serialize=False)),
                ('acc_num', models.IntegerField(unique=True)),
                ('father_name', models.CharField(blank=True, max_length=10, null=True)),
                ('national_code', models.IntegerField(unique=True)),
                ('is_ready_field', models.NullBooleanField(db_column='Is_Ready?')),
                ('address', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
                ('family', models.CharField(blank=True, max_length=16, null=True)),
                ('lat', models.IntegerField(blank=True, null=True)),
                ('lng', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'driver',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mont',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'mont',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mont2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'mont2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mont3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'mont3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SupportTable',
            fields=[
                ('sup_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('family', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'support_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TravelTable',
            fields=[
                ('trv_id', models.IntegerField(primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=20)),
                ('destinition', models.CharField(max_length=20)),
                ('number_2_dest', models.CharField(blank=True, db_column='2_Dest', max_length=20, null=True)),
                ('date', models.IntegerField()),
                ('grade', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'travel_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleTable',
            fields=[
                ('plate_number', models.IntegerField(primary_key=True, serialize=False)),
                ('colour', models.CharField(blank=True, max_length=10, null=True)),
                ('model', models.CharField(blank=True, max_length=10, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('insurance_expiration', models.IntegerField()),
            ],
            options={
                'db_table': 'vehicle_table',
                'managed': False,
            },
        ),
    ]
